apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: milvus
  annotations:
    addons.extensions.kubeblocks.io/default-is-empty: "true"
    meta.helm.sh/release-name: kubeblocks
    meta.helm.sh/release-namespace: kb-system
    xx.kubeblocks.io/kubeblocks-version: ">= 0.6.3"
    xx.kubeblocks.io/model: Vector-DBMS
  labels:
    app.kubernetes.io/instance: kubeblocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/version: 0.6.3
    helm.sh/chart: kubeblocks-0.6.3
    kubeblocks.io/provider: community
spec:
  description: 'Milvus is an open source (Apache-2.0 licensed) vector database built to power embedding similarity search and AI applications.'

  type: Helm

  helm:
#    chartLocationURL: "https://github.com/apecloud/helm-charts/releases/download/milvus-0.6.3/milvus-0.6.3.tgz"
    chartLocationURL: "https://jihulab.com/api/v4/projects/85949/packages/helm/stable/charts/milvus-0.6.3.tgz"


    installOptions:

  installable:
    autoInstall: false

  defaultInstallValues:
    - enabled: false
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"