apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.9.0'
  labels:
    addon.kubeblocks.io/model: vector
    addon.kubeblocks.io/name: milvus
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 0.9.2
  name: milvus
spec:
  defaultInstallValues:
  - enabled: true
  description: A cloud-native vector database, storage for next generation AI applications.
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/milvus-0.9.2.tgz
  installable:
    autoInstall: true
  type: Helm
