apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: llm
  annotations:
    addons.extensions.kubeblocks.io/default-is-empty: "true"
    xx.kubeblocks.io/kubeblocks-version: ">= 0.7.0"
    xx.kubeblocks.io/model: LLM
  labels:
    app.kubernetes.io/version: 0.7.0
    kubeblocks.io/provider: apecloud
spec:
  description: The large language model.
  type: Helm

  helm:
    # todo: 404 not found
    #    chartLocationURL: "https://github.com/apecloud/helm-charts/releases/download/llm-0.7.0/llm-0.7.0.tgz"
    chartLocationURL: "https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/llm-0.7.0.tgz"

    installOptions:

    valuesMapping:
      valueMap:
        replicaCount: replicaCount

      jsonMap:
        tolerations: tolerations

      resources:
        cpu:
          requests: resources.requests.cpu
          limits: resources.limits.cpu
        memory:
          requests: resources.requests.memory
          limits: resources.limits.memory

    defaultInstallValues:
      - replicas: 1
        tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"

    installable:
      autoInstall: false
