apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: neon
  annotations:
    addons.extensions.kubeblocks.io/default-is-empty: "true"
    meta.helm.sh/release-name: kubeblocks
    meta.helm.sh/release-namespace: kb-system
    xx.kubeblocks.io/kubeblocks-version: ">= 0.6.3"
    xx.kubeblocks.io/model: RDBMS
  labels:
    app.kubernetes.io/instance: kubeblocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/version: 0.6.3
    helm.sh/chart: kubeblocks-0.6.3
    kubeblocks.io/provider: community
spec:
  description: 'Neon is a fully managed serverless PostgreSQL with a generous free tier. Neon separates storage and compute and offers modern developer features such as serverless, branching, bottomless storage, and more. Before deploying neon, you must execute `kbcli addon enable cert-manager` command to deploy cert-manager.'

  type: Helm

  helm:
    {{- include "kubeblocks.addonChartLocationURL" ( dict "name" "neon" "version" (default .Chart.Version .Values.versionOverride) "values" .Values) | indent 4 }}
    {{- include "kubeblocks.addonChartsImage" . | indent 4 }}

    installOptions:
     {{- if hasPrefix "oci://" .Values.addonChartLocationBase }}
      version: {{ default .Chart.Version .Values.versionOverride }}
     {{- end }}

  installable:
    autoInstall: false

  defaultInstallValues:
    - enabled: true
