apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: opensearch
  annotations:
    addons.extensions.kubeblocks.io/default-is-empty: "true"
    meta.helm.sh/release-name: kubeblocks
    meta.helm.sh/release-namespace: kb-system
    xx.kubeblocks.io/kubeblocks-version: ">= 0.6.3"
    xx.kubeblocks.io/model: Search-Engine
  labels:
    app.kubernetes.io/instance: kubeblocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/version: 0.6.3
    helm.sh/chart: kubeblocks-0.6.3
    kubeblocks.io/provider: community
spec:
  description: 'OpenSearch is a scalable, flexible, and extensible open-source software suite for search, analytics, and observability applications licensed under Apache 2.0.'

  type: Helm

  helm:
    {{- include "kubeblocks.addonChartLocationURL" ( dict "name" "opensearch" "version" (default .Chart.Version .Values.versionOverride) "values" .Values) | indent 4 }}
    {{- include "kubeblocks.addonChartsImage" . | indent 4 }}

    installOptions:
      {{- if hasPrefix "oci://" .Values.addonChartLocationBase }}
      version: {{ default .Chart.Version .Values.versionOverride }}
      {{- end }}

  installable:
    autoInstall: false

  defaultInstallValues:
    - enabled: false
      {{- with .Values.tolerations }}
      tolerations: {{ toJson . | quote }}
      {{- end }}
