apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: victoria-metrics-agent
  annotations:
    addons.extensions.kubeblocks.io/default-is-empty: "true"
    meta.helm.sh/release-name: kubeblocks
    meta.helm.sh/release-namespace: kb-system
    addon.kubeblocks.io/kubeblocks-version: ">= 0.6.3"
    addon.kubeblocks.io/model: RDBMS
  labels:
    app.kubernetes.io/instance: kubeblocks
    app.kubernetes.io/managed-by: Helm
    addon.kubernetes.io/name: kubeblocks
    addon.kubernetes.io/version: 0.6.3
    helm.sh/chart: kubeblocks-0.6.3
    addon.kubeblocks.io/provider: community
spec:
  description: 'vmagent is a tiny agent which helps you collect metrics from various sources, relabel and filter the collected metrics and store them in VictoriaMetrics or any other storage systems via Prometheus remote_write protocol.'
  type: Helm

  helm:

    #    chartLocationURL: "https://github.com/apecloud/helm-charts/releases/download/victoria-metrics-agent-0.8.41/victoria-metrics-agent-0.8.41.tgz"
    chartLocationURL: "https://jihulab.com/api/v4/projects/85949/packages/helm/stable/charts/victoria-metrics-agent-0.8.41.tgz"

    installOptions:

    valuesMapping:
      valueMap:
        replicaCount: replicaCount

      jsonMap:
        tolerations: tolerations

      resources:
        cpu:
          requests: resources.requests.cpu
          limits: resources.limits.cpu
        memory:
          requests: resources.requests.memory
          limits: resources.limits.memory

  defaultInstallValues:
    - replicas: 1
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"

  installable:
    autoInstall: false