apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.7.0'
  labels:
    addon.kubeblocks.io/model: streaming
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/name: risingwave
    addon.kubeblocks.io/version: 0.7.0
  name: risingwave
spec:
  defaultInstallValues:
  - enabled: true
  description: RisingWave is a distributed SQL streaming database that enables cost-efficient
    and reliable processing of streaming data.
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/risingwave-0.7.0.tgz
  installable:
    autoInstall: true
  type: Helm
