apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.7.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: halo
    addon.kubeblocks.io/provider: "Halo-Tech \u7FB2\u548C\u6570\u636E\u5E93"
    addon.kubeblocks.io/version: 0.2.0
  name: halo
spec:
  defaultInstallValues:
  - enabled: true
  description: Halo cluster definition Helm chart for Kubernetes
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/halo-0.2.0.tgz
  installable:
    autoInstall: true
  type: Helm
