apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.7.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: mysql
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 0.8.1
  name: mysql
spec:
  defaultInstallValues:
  - enabled: true
  description: MySQL is a widely used, open-source relational database management
    system (RDBMS)
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/mysql-0.8.1.tgz
  installable:
    autoInstall: true
  type: Helm
