# copy from opsearch
apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: elasticsearch
  annotations:
    addons.extensions.kubeblocks.io/default-is-empty: "true"
    xx.kubeblocks.io/kubeblocks-version: ">= 0.7.0-beta.0"
    xx.kubeblocks.io/model: Search-Engine
  labels:
    app.kubernetes.io/version: 0.7.0-beta.0
    kubeblocks.io/provider: community
spec:
  description: 'Elasticsearch is a distributed search and analytics engine. It is used for web search, log monitoring, and real-time analytics. Ideal for Big Data applications.'

  type: Helm

  helm:
    #    chartLocationURL: "https://github.com/apecloud/helm-charts/releases/download/elasticsearch-0.7.0-beta.0/elasticsearch-0.7.0-beta.0.tgz"
    chartLocationURL: "https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/elasticsearch-0.7.0-beta.0.tgz"

  installable:
    autoInstall: false

  defaultInstallValues:
    - enabled: false
      tolerations: "[{\"effect\":\"NoSchedule\",\"key\":\"kb-controller\",\"operator\":\"Equal\",\"value\":\"true\"}]"
