apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.9.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: oracle
    addon.kubeblocks.io/provider: apecloud
    addon.kubeblocks.io/version: 1.0.0-alpha.0
  name: oracle
spec:
  defaultInstallValues:
  - enabled: true
  description: A Helm chart for Kubernetes
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/oracle-1.0.0-alpha.0.tgz
  installable:
    autoInstall: true
  type: Helm
