apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.8.0'
  labels:
    addon.kubeblocks.io/model: tsdb
    addon.kubeblocks.io/name: loki
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 0.9.1
  name: loki
spec:
  defaultInstallValues:
  - enabled: true
  description: Loki is a horizontally-scalable, highly-available, multi-tenant log
    aggregation system inspired by Prometheus. It is designed to be very cost effective
    and easy to operate.
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/loki-0.9.1.tgz
  installable:
    autoInstall: true
  type: Helm
