apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: victoria-metrics-agent
  annotations:
    addons.extensions.kubeblocks.io/default-is-empty: "true"
    meta.helm.sh/release-name: kubeblocks
    meta.helm.sh/release-namespace: kb-system
    xx.kubeblocks.io/kubeblocks-version: ">= 0.6.3"
    xx.kubeblocks.io/model: RDBMS
  labels:
    app.kubernetes.io/instance: kubeblocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/version: 0.6.3
    helm.sh/chart: kubeblocks-0.6.3
    kubeblocks.io/provider: community
spec:
  description: 'vmagent is a tiny agent which helps you collect metrics from various sources, relabel and filter the collected metrics and store them in VictoriaMetrics or any other storage systems via Prometheus remote_write protocol.'
  type: Helm

  helm:
    {{- include "kubeblocks.addonChartLocationURL" ( dict "name" "victoria-metrics-agent" "version" "0.8.41" "values" .Values) | indent 4 }}
    {{- include "kubeblocks.addonChartsImage" . | indent 4 }}

    installOptions:
      {{- if hasPrefix "oci://" .Values.addonChartLocationBase }}
      version: 0.8.41
      {{- end }}

    valuesMapping:
      valueMap:
        replicaCount: replicaCount

      jsonMap:
        tolerations: tolerations

      resources:
        cpu:
          requests: resources.requests.cpu
          limits: resources.limits.cpu
        memory:
          requests: resources.requests.memory
          limits: resources.limits.memory
  
  defaultInstallValues:
  - replicas: 1
    {{- with .Values.tolerations }}
    tolerations: {{ toJson . | quote }}
    {{- end }}

  installable:
    autoInstall: false 
