apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.9.0'
  labels:
    addon.kubeblocks.io/model: vector
    addon.kubeblocks.io/name: qdrant
    addon.kubeblocks.io/provider: apecloud
    addon.kubeblocks.io/version: 0.9.0
  name: qdrant
spec:
  defaultInstallValues:
  - enabled: true
  description: High-performance, massive-scale Vector Database for the next generation
    of AI.
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/qdrant-0.9.0.tgz
  installable:
    autoInstall: true
  type: Helm
