apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=1.0.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: mogdb
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 1.0.0
  name: mogdb
spec:
  defaultInstallValues:
  - enabled: true
  description: A Helm chart for Kubernetes
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/mogdb-1.0.0.tgz
  installable:
    autoInstall: true
  type: Helm
