apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=1.0.0'
  labels:
    addon.kubeblocks.io/model: message
    addon.kubeblocks.io/name: neo4j
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 1.0.1-beta.0
  name: neo4j
spec:
  defaultInstallValues:
  - enabled: true
  description: Neo4j is a highly scalable, robust native graph database.
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/neo4j-1.0.1-beta.0.tgz
  installable:
    autoInstall: true
  type: Helm
