apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  annotations:
    addon.kubeblocks.io/kubeblocks-version: '>=0.9.0'
  labels:
    addon.kubeblocks.io/model: RDBMS
    addon.kubeblocks.io/name: greatsql
    addon.kubeblocks.io/provider: community
    addon.kubeblocks.io/version: 0.1.0
  name: greatsql
spec:
  defaultInstallValues:
  - enabled: true
  description: GreatSQL is a high performance open source relational database management
    system  that can be used on common hardware for financial-grade application scenarios
  helm:
    chartLocationURL: https://jihulab.com/api/v4/projects/150246/packages/helm/stable/charts/greatsql-0.1.0.tgz
  installable:
    autoInstall: true
  type: Helm
