apiVersion: extensions.kubeblocks.io/v1alpha1
kind: Addon
metadata:
  name: redis
  annotations:
    addons.extensions.kubeblocks.io/default-is-empty: "true"
    meta.helm.sh/release-name: kubeblocks
    meta.helm.sh/release-namespace: kb-system
    xx.kubeblocks.io/kubeblocks-version: ">= 0.6.3"
    xx.kubeblocks.io/model: Key-value
  labels:
    app.kubernetes.io/instance: kubeblocks
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeblocks
    app.kubernetes.io/version: 0.6.3
    helm.sh/chart: kubeblocks-0.6.3
    kubeblocks.io/provider: community
spec:
  description: 'Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker.'

  type: Helm

  helm:
    {{- include "kubeblocks.addonChartLocationURL" ( dict "name" "redis" "version" (default .Chart.Version .Values.versionOverride) "values" .Values) | indent 4 }}
    {{- include "kubeblocks.addonChartsImage" . | indent 4 }}

    installOptions:
     {{- if hasPrefix "oci://" .Values.addonChartLocationBase }}
      version: {{ default .Chart.Version .Values.versionOverride }}
     {{- end }}

  installable:
    autoInstall: true

  defaultInstallValues:
    - enabled: true
